### ISSUE TITLE
Plan the App

### ISSUE THREAD

**Issue by fjgallard** [fjgallard/training-buddy#2]
- [ ] Create a Sitemap
- [ ] List the Components
- [ ] Plan the App Structure
- [ ] Generate the Components in the Angular App
